spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mybatis_test?useSSL=false&serverTimezone=UTC
    druid:
      initial-size: 5
      max-active: 10

mybatis:
  type-aliases-package: com.prger.domain
#  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true